name: NiSitterIDetDärVentriloOchSpelarDotA
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - absl-py==2.1.0
  - aider-chat==0.37.0
  - aiohttp==3.9.5
  - aiosignal==1.3.1
  - altair==5.3.0
  - annotated-types==0.6.0
  - anyio==4.3.0
  - asgiref==3.8.1
  - astunparse==1.6.3
  - attrs==23.2.0
  - backoff==2.2.1
  - beautifulsoup4==4.12.3
  - blinker==1.8.2
  - cachetools==5.3.3
  - certifi==2024.2.2
  - cffi==1.16.0
  - charset-normalizer==3.3.2
  - click==8.1.7
  - colorama==0.4.6
  - ConfigArgParse==1.7
  - contourpy==1.3.1
  - cryptography==42.0.8
  - cycler==0.12.1
  - diff-match-patch==20230430
  - diskcache==5.6.3
  - distro==1.9.0
  - Django==4.2.15
  - django-auditlog==3.0.0
  - django-filter==23.5
  - django-js-asset==3.0.1
  - django-mptt==0.14.0
  - djangorestframework==3.15.1
  - docopt==0.6.2
  - drf-excel==2.4.0
  - drf-flex-fields==1.0.2
  - einops==0.8.0
  - et_xmlfile==2.0.0
  - filelock==3.14.0
  - flake8==7.0.0
  - flatbuffers==24.12.23
  - fonttools==4.55.3
  - frozenlist==1.4.1
  - fsspec==2024.5.0
  - future==1.0.0
  - gast==0.6.0
  - gitdb==4.0.11
  - GitPython==3.1.43
  - google-ai-generativelanguage==0.6.4
  - google-api-core==2.19.0
  - google-api-python-client==2.129.0
  - google-auth==2.29.0
  - google-auth-httplib2==0.2.0
  - google-generativeai==0.5.4
  - google-pasta==0.2.0
  - googleapis-common-protos==1.63.0
  - greenlet==3.0.3
  - grep-ast==0.3.2
  - grpcio==1.63.0
  - grpcio-status==1.62.2
  - h11==0.14.0
  - h5py==3.12.1
  - httpcore==1.0.5
  - httplib2==0.22.0
  - httpx==0.27.0
  - huggingface-hub==0.26.5
  - HyperPyYAML==1.2.2
  - idna==3.7
  - importlib_metadata==7.1.0
  - Jinja2==3.1.4
  - joblib==1.4.2
  - jsonschema==4.22.0
  - jsonschema-specifications==2023.12.1
  - keras==3.8.0
  - kiwisolver==1.4.8
  - ldap3==2.9.1
  - libclang==18.1.1
  - lightning-utilities==0.11.9
  - litellm==1.37.16
  - llvmlite==0.43.0
  - mamba-ssm==file:///home/chen/mamba_ssm-2.2.4%2Bcu12torch2.5cxx11abiFALSE-cp312-cp312-linux_x86_64.whl
  - Markdown==3.7
  - markdown-it-py==3.0.0
  - MarkupSafe==2.1.5
  - matplotlib==3.10.0
  - mccabe==0.7.0
  - mdurl==0.1.2
  - ml-dtypes==0.4.1
  - mpmath==1.3.0
  - multidict==6.0.5
  - namex==0.0.8
  - NEMO==6.0.3
  - networkx==3.2.1
  - ninja==1.11.1.2
  - numba==0.60.0
  - numpy==1.26.4
  - nvidia-cublas-cu12==12.4.5.8
  - nvidia-cuda-cupti-cu12==12.4.127
  - nvidia-cuda-nvrtc-cu12==12.4.127
  - nvidia-cuda-runtime-cu12==12.4.127
  - nvidia-cudnn-cu12==9.1.0.70
  - nvidia-cufft-cu12==11.2.1.3
  - nvidia-curand-cu12==10.3.5.147
  - nvidia-cusolver-cu12==11.6.1.9
  - nvidia-cusparse-cu12==12.3.1.170
  - nvidia-nccl-cu12==2.21.5
  - nvidia-nvjitlink-cu12==12.4.127
  - nvidia-nvtx-cu12==12.4.127
  - openai==1.30.1
  - openpyxl==3.1.5
  - opt_einsum==3.4.0
  - optree==0.13.1
  - packaging==24.0
  - pandas==2.2.2
  - pathspec==0.12.1
  - pillow==10.3.0
  - playwright==1.44.0
  - prompt-toolkit==3.0.43
  - proto-plus==1.23.0
  - protobuf==4.25.3
  - pthflops==0.4.2
  - pyarrow==16.1.0
  - pyasn1==0.6.0
  - pyasn1_modules==0.4.0
  - pycodestyle==2.11.1
  - pycparser==2.22
  - pydantic==2.7.1
  - pydantic_core==2.18.2
  - pydeck==0.9.1
  - pyDeprecate==0.3.1
  - pyee==11.1.0
  - pyflakes==3.2.0
  - Pygments==2.18.0
  - pykwalify==1.8.0
  - pymodbus==3.3.2
  - pypandoc==1.13
  - pyparsing==3.1.2
  - python-dateutil==2.9.0
  - python-dotenv==1.0.1
  - python_speech_features==0.6
  - pytorch-lightning==1.8.4
  - pytz==2024.1
  - PyYAML==6.0.1
  - referencing==0.35.1
  - regex==2024.5.15
  - requests==2.32.3
  - resampy==0.4.3
  - rich==13.7.1
  - rpds-py==0.18.1
  - rsa==4.9
  - ruamel.yaml==0.18.6
  - ruamel.yaml.clib==0.2.8
  - safetensors==0.4.5
  - scikit-learn==1.6.0
  - scipy==1.13.0
  - seaborn==0.13.2
  - sentencepiece==0.2.0
  - setuptools==75.1.0
  - six==1.16.0
  - smmap==5.0.1
  - sniffio==1.3.1
  - sounddevice==0.4.6
  - soundfile==0.12.1
  - soupsieve==2.5
  - speechbrain==1.0.2
  - sqlparse==0.5.3
  - streamlit==1.34.0
  - sympy==1.13.1
  - tenacity==8.3.0
  - tensorboard==2.18.0
  - tensorboard-data-server==0.7.2
  - tensorboardX==2.6.2.2
  - tensorflow==2.18.0
  - termcolor==2.5.0
  - threadpoolctl==3.5.0
  - tiktoken==0.7.0
  - tokenizers==0.21.0
  - toml==0.10.2
  - toolz==0.12.1
  - torch==2.5.1
  - torchaudio==2.5.1
  - torchmetrics==0.9.1
  - torchsummary==1.5.1
  - tornado==6.4
  - tqdm==4.66.4
  - transformers==4.47.0
  - tree-sitter==0.21.3
  - tree-sitter-languages==1.10.2
  - triton==3.1.0
  - typing_extensions==4.11.0
  - tzdata==2024.1
  - uritemplate==4.1.1
  - urllib3==2.2.1
  - watchdog==4.0.1
  - wcwidth==0.2.13
  - Werkzeug==3.1.3
  - west==1.2.0
  - wheel==0.45.1
  - wrapt==1.17.1
  - yarl==1.9.4
  - zipp==3.18.2
