for (int i = 0; i < 42; i++)
  for (int ii = 0; ii < 42; ii++)
    for (int iii = 0; iii < 42; iii++)
      for (int iiii = 0; iiii < 42; iiii++)
        for (int iiiii = 0; iiiii < 42; iiiii++)
          for (int iiiiii = 0; iiiiii < 42; iiiiii++)
            for (int iiiiiii = 0; iiiiiii < 42; iiiiiii++)
              for (int iiiiiiii = 0; iiiiiiii < 42; iiiiiiii++)
                for (int iiiiiiiii = 0; iiiiiiiii < 42; iiiiiiiii++)
                  for (int iiiiiiiiii = 0; iiiiiiiiii < 42; iiiiiiiiii++)
                    for (int iiiiiiiiiii = 0; iiiiiiiiiii < 42; iiiiiiiiiii++)
                      for (int iiiiiiiiiiii = 0; iiiiiiiiiiii < 42; iiiiiiiiiiii++)
                        for (int iiiiiiiiiiiii = 0; iiiiiiiiiiiii < 42; iiiiiiiiiiiii++)
                          for (int iiiiiiiiiiiiii = 0; iiiiiiiiiiiiii < 42; iiiiiiiiiiiiii++)
                            for (int iiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiii++)
                              for (int iiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiii++)
                                for (int iiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiii++)
                                  for (int iiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiii++)
                                    for (int iiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiii++)
                                      for (int iiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiii++)
                                        for (int iiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiii++)
                                          for (int iiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiii++)
                                            for (int iiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiii++)
                                              for (int iiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiii++)
                                                for (int iiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiii++)
                                                  for (int iiiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiiii++)
                                                    for (int iiiiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiiiii++)
                                                      for (int iiiiiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiiiiii++)
                                                        for (int iiiiiiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiiiiiii++)
                                                          for (int iiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiiiiiiii++)
                                                            for (int iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 0; iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii < 42; iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii++)                             





